package org.yanbwe.modularshoot.client.render;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.logging.LogUtils;
import java.util.UUID;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.geom.EntityModelSet;
import net.minecraft.client.renderer.BlockEntityWithoutLevelRenderer;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher;
import net.minecraft.client.renderer.entity.ItemRenderer;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.client.resources.model.ModelManager;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.core.RegistryAccess;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemDisplayContext;
import net.minecraft.world.item.ItemStack;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.yanbwe.modularshoot.ModularShootAPI;
import org.yanbwe.modularshoot.registry.gun.GunDefinition;

/**
 * Custom item renderer for framework guns, integrating shoot-texture
 * switching with the vanilla item rendering pipeline.
 *
 * <p>The design doc (§渲染器, line 1337-1339) mandates that guns use the
 * vanilla item render pipeline with automatic texture extrusion &mdash; no
 * custom model loader, no external model library. This renderer achieves
 * texture switching <em>within</em> that constraint by acting as a thin
 * interceptor: the gun item's baked model is flagged with
 * {@code custom_renderer: true}, which causes {@link ItemRenderer#render}
 * to delegate to {@link #renderByItem}. This override then selects the
 * correct baked model (base or shoot texture) via {@link ShootTextureResolver}
 * and hands it back to the vanilla {@code ItemRenderer.render} for normal
 * extrusion and drawing.</p>
 *
 * <h2>Extension point</h2>
 * <p>NeoForge 1.21.1 exposes custom item rendering through
 * {@link BlockEntityWithoutLevelRenderer}, registered per-item via
 * {@code IClientItemExtensions.getCustomRenderer()} (fired on the mod event
 * bus through {@code RegisterClientExtensionsEvent}). The gun item's model
 * JSON must set {@code "neoforge:custom_renderer": true} (or equivalent)
 * so that {@link BakedModel#isCustomRenderer()} returns {@code true},
 * routing rendering into this class.</p>
 *
 * <h2>Render flow</h2>
 * <ol>
 *   <li>The vanilla pipeline calls {@link #renderByItem} because the gun's
 *       baked model reports {@code isCustomRenderer() == true}.</li>
 *   <li>This method reads the {@link GunDefinition} from the stack's
 *       {@code gun_data} component and the holding player's uuid.</li>
 *   <li>{@link ShootTextureResolver#resolveTexture} selects the base or
 *       shoot texture based on the gun's {@code shoot_texture_mode} and the
 *       player's shoot state.</li>
 *   <li>The baked model for the resolved texture is looked up from the
 *       {@link ModelManager}. These per-gun models are generated by the
 *       model-generation subtask and registered at a convention-based
 *       {@link ModelResourceLocation} (see {@link #resolveBakedModel}).</li>
 *   <li>The vanilla {@link ItemRenderer#render} is called with the selected
 *       model. Because the selected model has {@code isCustomRenderer() == false},
 *       the vanilla pipeline renders it normally (extrusion, foil, lighting)
 *       without recursing back into this renderer.</li>
 * </ol>
 *
 * <h2>First-person vs third-person</h2>
 * <p>The vanilla pipeline calls {@code renderByItem} for both first-person
 * (held in hand) and third-person (on the player model) contexts. The
 * {@link ItemDisplayContext} parameter distinguishes them. Both paths use
 * the same texture-resolution logic, satisfying the design doc requirement
 * that texture switching is the sole visual feedback in first person and
 * also applies in third person (设计文档 line 1343-1344).</p>
 *
 * <h2>Player context</h2>
 * <p>{@code renderByItem} does not receive the holding {@code LivingEntity}
 * as a parameter (a vanilla API limitation). For the local player
 * (first-person) we fall back to {@code Minecraft.getInstance().player}.
 * For remote players (third-person) a {@link ThreadLocal} context is
 * provided: a Mixin on {@code ItemRenderer.renderStatic} sets the rendering
 * player's uuid before the call and clears it afterwards
 * (see {@link #setRenderingPlayer} / {@link #clearRenderingPlayer}).</p>
 *
 * <p><strong>Client-only class.</strong> References to {@link Minecraft},
 * {@link ItemRenderer} and other client types restrict this class to the
 * physical client. It must only be instantiated and registered via
 * {@code IClientItemExtensions} on the client mod event bus.</p>
 *
 * @see ShootTextureResolver
 * @see BlockEntityWithoutLevelRenderer
 * @see PlayerShootStateManager
 */
public final class GunItemRenderer extends BlockEntityWithoutLevelRenderer {

    private static final Logger LOGGER = LogUtils.getLogger();

    /** Fallback uuid used when no player context is available (e.g. menu). */
    private static final UUID NULL_UUID = new UUID(0L, 0L);

    /**
     * ThreadLocal tracking the uuid of the player whose held item is
     * currently being rendered.
     *
     * <p>Set by a Mixin/event hook before {@link ItemRenderer#render} calls
     * {@link #renderByItem} and cleared afterwards. This bridges the vanilla
     * API gap where {@code renderByItem} does not receive the holding
     * entity. When unset, the renderer falls back to the local player
     * (correct for first-person) or {@link #NULL_UUID} (yields base texture
     * for menu/creative-tab rendering).</p>
     */
    private static final ThreadLocal<UUID> RENDERING_PLAYER_UUID = new ThreadLocal<>();

    private final ItemRenderer itemRenderer;

    /**
     * Constructs the renderer with the vanilla dispatcher and model set.
     *
     * <p>Intended to be called from
     * {@code IClientItemExtensions.getCustomRenderer()} during
     * {@code RegisterClientExtensionsEvent}. The caller should pass the
     * instances available from
     * {@code Minecraft.getInstance().getBlockEntityRenderDispatcher()} and
     * {@code Minecraft.getInstance().getEntityModels()}.</p>
     *
     * @param dispatcher the block-entity render dispatcher
     * @param modelSet   the entity model set
     */
    public GunItemRenderer(BlockEntityRenderDispatcher dispatcher, EntityModelSet modelSet) {
        super(dispatcher, modelSet);
        this.itemRenderer = Minecraft.getInstance().getItemRenderer();
    }

    /**
     * Sets the uuid of the player whose held item is about to be rendered.
     *
     * <p>Intended to be called by a Mixin on
     * {@link ItemRenderer#renderStatic} before the call to
     * {@code renderByItem}. This enables correct shoot-texture resolution
     * for remote players in third-person. When the render completes the
     * caller must invoke {@link #clearRenderingPlayer} to avoid leaking
     * context into subsequent renders.</p>
     *
     * @param uuid the rendering player's uuid, or {@code null} to clear
     */
    public static void setRenderingPlayer(@Nullable UUID uuid) {
        RENDERING_PLAYER_UUID.set(uuid);
    }

    /**
     * Clears the rendering-player context after a render completes.
     *
     * <p>Must be called in a {@code finally} block by the same Mixin that
     * called {@link #setRenderingPlayer} to prevent context leakage.</p>
     */
    public static void clearRenderingPlayer() {
        RENDERING_PLAYER_UUID.remove();
    }

    /**
     * Custom render entry point invoked by the vanilla pipeline when the
     * gun's baked model reports {@code isCustomRenderer() == true}.
     *
     * <p>Resolves the correct texture via {@link ShootTextureResolver},
     * looks up the corresponding baked model, and delegates back to the
     * vanilla {@link ItemRenderer#render} for normal extrusion and drawing.
     * This keeps the gun visually consistent with vanilla items while
     * adding shoot-texture switching as the sole dynamic element.</p>
     *
     * @param stack        the gun item stack
     * @param context      the display context (first-person, third-person,
     *                     GUI, etc.)
     * @param poseStack    the pose stack
     * @param bufferSource the buffer source
     * @param light        the packed light value
     * @param overlay      the packed overlay value
     */
    @Override
    public void renderByItem(
            ItemStack stack,
            ItemDisplayContext context,
            PoseStack poseStack,
            MultiBufferSource bufferSource,
            int light,
            int overlay) {

        ResourceLocation gunId = ModularShootAPI.getGunId(stack);
        if (gunId == null) {
            renderFallback(stack, context, poseStack, bufferSource, light, overlay);
            return;
        }

        GunDefinition gunDef = resolveGunDefinition(gunId);
        if (gunDef == null) {
            renderFallback(stack, context, poseStack, bufferSource, light, overlay);
            return;
        }

        UUID playerUuid = resolvePlayerUuid();
        ResourceLocation texture = ShootTextureResolver.resolveTexture(gunDef, playerUuid);
        boolean useShootTexture = gunDef.shootTexture().isPresent()
                && texture.equals(gunDef.shootTexture().get());

        BakedModel model = resolveBakedModel(gunId, useShootTexture);
        itemRenderer.render(stack, context, false, poseStack, bufferSource, light, overlay, model);
    }

    /**
     * Reads the {@link GunDefinition} for the given gun id from the
     * {@code modularshoot:guns} registry.
     *
     * <p>Returns {@code null} when the registry is unavailable (e.g. on the
     * main menu where the world is not yet loaded) or the id is not
     * registered. In that case the caller should fall back to a safe
     * default render.</p>
     *
     * @param gunId the gun definition id
     * @return the gun definition, or {@code null} when it cannot be resolved
     */
    @Nullable
    private GunDefinition resolveGunDefinition(ResourceLocation gunId) {
        Minecraft minecraft = Minecraft.getInstance();
        if (minecraft.level == null) {
            return null;
        }
        RegistryAccess registryAccess = minecraft.level.registryAccess();
        return ModularShootAPI.getGunDefinition(registryAccess, gunId).orElse(null);
    }

    /**
     * Determines the uuid of the player whose held item is being rendered.
     *
     * <p>Checks the {@link #RENDERING_PLAYER_UUID} ThreadLocal first (set by
     * a Mixin for third-person remote-player rendering). When unset, falls
     * back to the local player (correct for first-person). When neither is
     * available (e.g. menu rendering), returns {@link #NULL_UUID} which
     * causes {@link ShootTextureResolver} to select the base texture.</p>
     *
     * @return the rendering player's uuid (never {@code null})
     */
    private UUID resolvePlayerUuid() {
        UUID tracked = RENDERING_PLAYER_UUID.get();
        if (tracked != null) {
            return tracked;
        }
        Minecraft minecraft = Minecraft.getInstance();
        return minecraft.player != null ? minecraft.player.getUUID() : NULL_UUID;
    }

    /**
     * Looks up the baked model for the gun's base or shoot texture.
     *
     * <p><b>Model location convention (TODO: coordinate with model-generation
     * subtask):</b> per-gun item models are registered at</p>
     * <ul>
     *   <li>Base: {@code <namespace>:gun/<path>#inventory}</li>
     *   <li>Shoot: {@code <namespace>:gun/<path>_shoot#inventory}</li>
     * </ul>
     * <p>where {@code <namespace>:<path>} is the gun definition id. For
     * example, gun {@code modularshoot:sniper_rifle} uses</p>
     * <ul>
     *   <li>Base model: {@code modularshoot:gun/sniper_rifle#inventory}</li>
     *   <li>Shoot model: {@code modularshoot:gun/sniper_rifle_shoot#inventory}</li>
     * </ul>
     *
     * <p>The model JSON at these locations should be a standard
     * {@code minecraft:item/generated} model referencing the corresponding
     * texture, with {@code custom_renderer} left at its default
     * ({@code false}) so the vanilla pipeline renders it normally without
     * recursing into this renderer.</p>
     *
     * <p>When the resolved model reports {@code isCustomRenderer() == true}
     * (misconfigured model JSON) the missing model is substituted to
     * prevent infinite recursion and a warning is logged.</p>
     *
     * @param gunId          the gun definition id, used to derive the model
     *                      location
     * @param useShootTexture {@code true} to select the shoot-texture model,
     *                       {@code false} for the base-texture model
     * @return a non-custom baked model suitable for vanilla rendering
     */
    private BakedModel resolveBakedModel(ResourceLocation gunId, boolean useShootTexture) {
        String modelPath = useShootTexture
                ? "gun/" + gunId.getPath() + "_shoot"
                : "gun/" + gunId.getPath();
        ModelResourceLocation modelLocation =
                ModelResourceLocation.inventory(ResourceLocation.fromNamespaceAndPath(gunId.getNamespace(), modelPath));

        ModelManager modelManager = itemRenderer.getItemModelShaper().getModelManager();
        BakedModel model = modelManager.getModel(modelLocation);

        // Guard against recursion: if the resolved model is also a custom
        // renderer, rendering it would re-enter renderByItem infinitely.
        if (model.isCustomRenderer()) {
            LOGGER.warn("Gun model at {} has custom_renderer=true; using missing model to avoid recursion", modelLocation);
            return modelManager.getMissingModel();
        }

        return model;
    }

    /**
     * Fallback render path used when the gun definition cannot be resolved
     * (e.g. on the main menu or when the registry is empty).
     *
     * <p>Renders the item with the vanilla missing model so the player sees
     * the standard black-and-purple pattern rather than nothing. This is a
     * safe, non-recursive default: the missing model has
     * {@code isCustomRenderer() == false}.</p>
     *
     * @param stack        the gun item stack
     * @param context      the display context
     * @param poseStack    the pose stack
     * @param bufferSource the buffer source
     * @param light        the packed light value
     * @param overlay      the packed overlay value
     */
    private void renderFallback(
            ItemStack stack,
            ItemDisplayContext context,
            PoseStack poseStack,
            MultiBufferSource bufferSource,
            int light,
            int overlay) {

        BakedModel missingModel = itemRenderer.getItemModelShaper().getModelManager().getMissingModel();
        itemRenderer.render(stack, context, false, poseStack, bufferSource, light, overlay, missingModel);
    }
}
