package org.yanbwe.modularshoot.registry.gun;

import java.util.Optional;
import net.minecraft.resources.ResourceLocation;
import org.jetbrains.annotations.NotNull;

/**
 * Dynamic source of gun definitions queried by
 * {@link GunRegistry#getGun(net.minecraft.core.RegistryAccess, ResourceLocation)}
 * between the Java API map and the datapack registry
 * (改进① 动态定义来源, 2026-08-10 探讨整理).
 *
 * <p>The datapack registry and the Java API map both key definitions by a
 * <em>global</em> gun id; a provider lifts that constraint by supplying
 * definitions that are computed at query time — per-player, per-instance,
 * or generated by other mods' runtime logic. The gun id may encode the
 * source (e.g. {@code player:<uuid>}) so the provider can recover the
 * context it needs.</p>
 *
 * <p>Contract:</p>
 * <ul>
 *   <li>Return {@link Optional#empty()} for ids this provider does not
 *       handle; the framework then falls through to the next source
 *       (datapack registry), preserving the existing degradation path.</li>
 *   <li>Providers run in registration order; the first non-empty result
 *       wins. Java-API-registered definitions always take priority over
 *       providers (设计文档 §注册冲突与覆盖 语义延伸).</li>
 *   <li>Implementations must be side-safe (no client-only calls) because
 *       {@code getGun} runs on both sides.</li>
 * </ul>
 *
 * <p>Registration is process-wide and survives {@code /reload}; use
 * {@link GunRegistry#registerGunDefinitionProvider} (or the
 * {@code ModularShootAPI} facade).</p>
 */
@FunctionalInterface
public interface GunDefinitionProvider {

    /**
     * Resolves a gun definition for the given id, or empty when this
     * provider does not handle the id.
     *
     * @param gunId the gun definition id being looked up
     * @return the definition, or empty to fall through to the next source
     */
    @NotNull
    Optional<GunDefinition> get(@NotNull ResourceLocation gunId);
}
